CREATE DATABASE IF NOT EXISTS devcorptravel CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
USE devcorptravel;
CREATE TABLE IF NOT EXISTS lookup_status (status_key VARCHAR(40) PRIMARY KEY) ENGINE=InnoDB;
INSERT IGNORE INTO lookup_status (status_key) VALUES
('active'),('inactive'),('deleted'),('draft'),('published'),('pending'),('confirmed'),('canceled'),('completed');
CREATE TABLE IF NOT EXISTS lookup_mode (mode_key VARCHAR(20) PRIMARY KEY) ENGINE=InnoDB;
INSERT IGNORE INTO lookup_mode (mode_key) VALUES ('flights'),('hotels'),('cars');
CREATE TABLE IF NOT EXISTS organizations (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, external_id VARCHAR(64) UNIQUE, name VARCHAR(200), domain VARCHAR(200), status VARCHAR(40) DEFAULT 'active') ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS users (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, org_id BIGINT UNSIGNED NOT NULL, email VARCHAR(254) NOT NULL, display_name VARCHAR(200), auth_provider VARCHAR(40), password_hash VARCHAR(255), INDEX(org_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS roles (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, org_id BIGINT UNSIGNED NULL, name VARCHAR(100) NOT NULL, UNIQUE KEY (org_id, name)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS user_roles (user_id BIGINT UNSIGNED NOT NULL, role_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(user_id, role_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS permissions (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, code VARCHAR(120) UNIQUE) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS role_permissions (role_id BIGINT UNSIGNED NOT NULL, permission_id BIGINT UNSIGNED NOT NULL, PRIMARY KEY(role_id, permission_id)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS travelers (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, org_id BIGINT UNSIGNED NOT NULL, user_id BIGINT UNSIGNED NULL, email VARCHAR(254), given_name VARCHAR(100), family_name VARCHAR(100)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS policies (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, org_id BIGINT UNSIGNED NOT NULL, name VARCHAR(200), status VARCHAR(40) DEFAULT 'draft') ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS policy_versions (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, policy_id BIGINT UNSIGNED NOT NULL, version_num INT NOT NULL, status VARCHAR(40) DEFAULT 'draft') ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS policy_rules (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, policy_version_id BIGINT UNSIGNED NOT NULL, rule_key VARCHAR(120), rule_op VARCHAR(8), rule_value VARCHAR(255)) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS bookings (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, org_id BIGINT UNSIGNED NOT NULL, traveler_id BIGINT UNSIGNED NOT NULL, arranger_user_id BIGINT UNSIGNED NULL, status VARCHAR(40), total_amount DECIMAL(12,2) DEFAULT 0, total_currency CHAR(3) DEFAULT 'USD', confirmation_code VARCHAR(64), created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS booking_items (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, booking_id BIGINT UNSIGNED NOT NULL, mode VARCHAR(20), supplier_ref VARCHAR(200), is_in_policy TINYINT(1) DEFAULT 1, price_amount DECIMAL(12,2), price_currency CHAR(3) DEFAULT 'USD', item_json JSON) ENGINE=InnoDB;
CREATE TABLE IF NOT EXISTS trips (id BIGINT UNSIGNED PRIMARY KEY AUTO_INCREMENT, org_id BIGINT UNSIGNED NOT NULL, traveler_id BIGINT UNSIGNED NOT NULL, booking_id BIGINT UNSIGNED NOT NULL, start_date DATE, end_date DATE, status VARCHAR(40)) ENGINE=InnoDB;
INSERT IGNORE INTO permissions (code) VALUES ('policy.read'),('policy.write'),('policy.publish'),('user.manage'),('arranger.manage'),('traveler.read'),('traveler.write'),('profile.read'),('profile.write'),('search.execute'),('booking.create'),('booking.cancel'),('trip.read'),('trip.write'),('report.read'),('report.export'),('notifications.send'),('webhook.manage'),('audit.read');
INSERT IGNORE INTO roles (org_id, name) VALUES (NULL,'OrgAdmin'),(NULL,'TravelManager'),(NULL,'Arranger'),(NULL,'Traveler');
INSERT IGNORE INTO organizations (external_id, name, domain, status) VALUES ('acme-001','Acme Corporation','acme.com','active');
SET @org := (SELECT id FROM organizations WHERE external_id='acme-001');
INSERT IGNORE INTO roles (org_id, name) VALUES (@org,'OrgAdmin'),(@org,'TravelManager'),(@org,'Arranger'),(@org,'Traveler');
INSERT IGNORE INTO policies (org_id, name, status) VALUES (@org, 'Global Default', 'draft');
SET @pol := (SELECT id FROM policies WHERE org_id=@org AND name='Global Default');
INSERT IGNORE INTO policy_versions (policy_id, version_num, status) VALUES (@pol,1,'published');
SET @pv := (SELECT id FROM policy_versions WHERE policy_id=@pol AND version_num=1);
INSERT IGNORE INTO policy_rules (policy_version_id, rule_key, rule_op, rule_value) VALUES (@pv,'hotel.max_nightly_rate','<=','250'),(@pv,'flights.allowed_cabins','in','Economy,PremiumEconomy');
