name: DB Demo (Flyway, manual)
on: workflow_dispatch
jobs:
  demo-seed:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install mysql client
        run: sudo apt-get update && sudo apt-get install -y mysql-client
      - name: Apply demo seed
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT || 3306 }}
          MYSQL_DB: ${{ secrets.MYSQL_DB || 'devcorptravel' }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          mysql -h "$MYSQL_HOST" -P "$MYSQL_PORT" -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DB" < devcorptravel_sql/devcorptravel_demo_seed.sql
  demo-cleanup:
    runs-on: ubuntu-latest
    needs: demo-seed
    steps:
      - uses: actions/checkout@v4
      - name: Install mysql client
        run: sudo apt-get update && sudo apt-get install -y mysql-client
      - name: Cleanup demo seed
        env:
          MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
          MYSQL_PORT: ${{ secrets.MYSQL_PORT || 3306 }}
          MYSQL_DB: ${{ secrets.MYSQL_DB || 'devcorptravel' }}
          MYSQL_USER: ${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
        run: |
          mysql -h "$MYSQL_HOST" -P "$MYSQL_PORT" -u "$MYSQL_USER" -p"$MYSQL_PASSWORD" "$MYSQL_DB" < devcorptravel_sql/devcorptravel_demo_cleanup.sql
